### ISSUE TITLE
PyGitHub 

### ISSUE THREAD

**Issue by santacruzm** [GatorCogitate/cogitate_tool#2]
https://github.com/PyGithub/PyGithub

Research and create Demo by next week

**Comment by bagashvilit** [comment]
Hi everyone, I added some configuration files to our branch. I also added a sample demo from PyGithub. Please see `demo.py`. We should probably add more features.
Also according to the [website](https://pygithub.readthedocs.io/en/latest/introduction.html), PyGithub is a python library to use [Github API v3](https://developer.github.com/v3/). Maybe we should research more about it.

**Comment by cklima616** [comment]
@bagashvilit Thank you Teona! I will do some research on alternative tools, just to make sure this is the most effective. In addition, I will look more into GitHub API v3. I don't know what that will look like in terms of commits, but will keep you posted in here.

**Comment by bagashvilit** [comment]
@cklima616 I also have some issues with configuring PyGithub, please let me know if you make it work.

**Comment by bagashvilit** [comment]
Should we add `.travis.yml`?

**Comment by Jordan-A** [comment]
Great idea to add the default demo! I can also do research on different tools and add to the demo file.

**Comment by cklima616** [comment]
@bagashvilit I don't think travis.yml is necessary! I'm about to attempt to configure it. Did anyone find any alternatives? I didn't find any that were viable.

**Comment by cklima616** [comment]
Hey everyone, I tried running our demo file, but I am having difficulty because I am getting this error:
```Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    from github import Github
ModuleNotFoundError: No module named 'github' ```
I installed PyGithub with pip, so I'm not sure why this may be. I found this [issue] (https://github.com/PyGithub/PyGithub/issues/856). Let me know if people are having a similar issue. The solution might be running it with Python 3.6 instead of 3.7, according to the issue tracker.

**Comment by noorbuchi** [comment]
Hi @cklima616 ! I don't mean to intervene in your demo or your branch, but I might be able to help since we had a similar issue in our branch. I would suggest that you include the packages in your pipfile then running the `pipenv install --dev` which would install all of the packages in the pipfile dev section. A portion of the pipfile would look something like this
```
[dev-packages]
fastapi = "*"
uvicorn = "*"
black = "*"
pylint = "*"
flake8 = "*"
pydocstyle = "*"
pytest = "*"
PyGithub = "*"
```
I hope this is helpful

**Comment by cklima616** [comment]
@noorbuchi Thank you! While this makes sense, I am getting a pretty nasty error message. I tried reverting the code back to what @bagashvilit initially committed, and this is what I get:
```
Traceback (most recent call last):
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/sitstatic/.pyenv/versions/3.7.6/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1110bc1d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='%7bhostname%7d', port=443): Max retries exceeded with url: /api/v3/user/repos (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1110bc1d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    for repo in g.get_user().get_repos():
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/github/PaginatedList.py", line 62, in __iter__
    newElements = self._grow()
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/github/PaginatedList.py", line 74, in _grow
    newElements = self._fetchNextPage()
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/github/PaginatedList.py", line 205, in _fetchNextPage
    "GET", self.__nextUrl, parameters=self.__nextParams, headers=self.__headers
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/github/Requester.py", line 322, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/github/Requester.py", line 413, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/github/Requester.py", line 475, in __requestEncode
    cnx, verb, url, requestHeaders, encoded_input
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/github/Requester.py", line 501, in __requestRaw
    response = cnx.getresponse()
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/github/Requester.py", line 119, in getresponse
    allow_redirects=False,
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/sitstatic/.local/share/virtualenvs/cogitate_tool-XHXeYpWb/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='%7bhostname%7d', port=443): Max retries exceeded with url: /api/v3/user/repos (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1110bc1d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```
I will hold off on pushing these changes in the meantime, but if anyone has any ideas on what this means, that would be super.

**Comment by cklima616** [comment]
My guess would be it involves either a) declaring the initial variables or 2) defining the base_url.

**Comment by noorbuchi** [comment]
These are some overwhelming error messages for sure. I hope you can get them fixed soon. While I was reading some of your code I noticed some issues that we also encountered while implementing elements of the PyGitHub into our demo. The first issue that I see is the instantiation of multiple invalid GitHub objects. While you can use either of the three methods of authentication, you can't use all of them at the same time on the same object. I wasn't successful in using the username and password method (I read that they stopped supporting it) so I used the GitHub token method (you can generate it [here](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line)) which brings me to the second issue. In order to display the repos, issues, and the branches, you need to have an authenticated user. This means that you'll need to figure out a way to generate a token and input that token in your Github object instantiation. After solving the previous issues, you might encounter others that involve the PyGitHub API. I suggest that you consult [this](https://pygithub.readthedocs.io/en/latest/github_objects.html) website that includes the docs for the PyGitHub package. It might also be worth exploring the side menu of that website to get more information.

**Comment by cklima616** [comment]
@noorbuchi Thank you for explaining the access token! I updated our branch, and was able to get it to run. It looks like for each user, we would need an access token - so right now, the program prints the repos in my personal GitHub.

**Comment by cklima616** [comment]
Okay, new problem: GitHub revoked my access token because they saw that I committed it to our repo? So I can make a new one for the demo to work, but I don't think it's a viable option to use that method in the future. Something we can all talk about.

**Comment by bagashvilit** [comment]
@cklima616  I am still unable to run `demo.py`. What commands did you use to configure the `PyGithub`, or to run the program

**Comment by cklima616** [comment]
@bagashvilit it's because GitHub revoked the access token I use in the repo. They will revoke them if we commit them to a repo for privacy reasons.

**Comment by cklima616** [comment]
@bagashvilit I just committed an updated demo! To make it run, do this:
1. In your GitHub, click on your icon and go to Settings -> Developer Settings -> Personal Access Tokens to generate an access token. It will ask you to select what the token should actually give access to - I did everything except for "add" and "delete" methods.
2. In the source code, replace my access token (a bunch of random numbers and letters) with your own. 
3. Run pipenv install --dev
4. Run pipenv run python demo.py 

Make sure you are in our branch, and that you have accepted the invitation to the cogitate tool! Right now, our demo shows how to access repos, list open issues, and list branches.

**Comment by cklima616** [comment]
The above steps should work for everyone! Again, if you commit to the repo with your access token, GitHub will revoke access rights to it. This is just to keep information safe, but it is kind of annoying. It is something to consider. If someone is not sure what to work on, it might be useful to learn more about Github Enterprise? The third accessor method listed in that short intro involves Github Enterprise, and as Noor stated earlier, the username and password method is not very reliable.

**Comment by bagashvilit** [comment]
Thank you @cklima616, I got it to work. Also, a quick note to people who tried `pip install pygithub`  command and have trouble, try using `python -m pip install pygithub` instead.

**Comment by bagashvilit** [comment]
We should also update `README.md`, so that it's clear for other team members how to use the tool

**Comment by noorbuchi** [comment]
@bagashvilit  @cklima616  you can solve this issue by adding the packages you need to the pipfile so when the `pipenv install --dev` command is run, all of the dev packages are installed correctly

**Comment by cklima616** [comment]
@noorbuchi We updated the Pipfile already, but thank you!

**Comment by santacruzm** [comment]
@cklima616 I am working on running the demo now. And a question came up what file within the source code did you go ahead and added in your access token? I added mine within the demo.py file and committed it to the repo, but it is still not working within our branch.

**Comment by santacruzm** [comment]
Also, @cklima616 Thank you for sharing the step by step guide as I was also having the same issues regarding running the demo.py.

**Comment by santacruzm** [comment]
Here is some research on **[Github Enterprise](https://enterprise.github.com/faq)**: 

**GitHub Enterprise's Features**

- Compliance and auditing
- Hundreds of integrations
- Flexible deployment
- Centralized permissions
- Powerful dashboards
- Technical support

**What it is?** 

GitHub Enterprise is the on-premises version of GitHub.com. In other words, GitHub keeps all of their IT environment onsite managed by themselves or a third party. GitHub Enterprise is a tool in the Code Collaboration & Version Control category of a tech stack. It makes collaborative coding possible and enjoyable for large-scale software development teams. GitHub Enterprise includes similar feature sets as GitHub.com but packaged for running on your organization's local network.

**When to use it**

We should ultimately use **GitHub Enterprise** when teams need complete control over repository and project information. To configure a GitHub Enterprise repository, first, proceed to add the repository and select GitHub Enterprise.

1. Link Your GitHub Enterprise Account
2. Provide Repository Information
3. Choose a Bug Tracker
4. Manage Access Control
5. Save the Repository

**Alternatives to GitHub Enterprise**

- Bitbucket

Bitbucket gives teams one place to plan projects, collaborate on code, test and deploy, all with free private Git repositories. Teams choose Bitbucket because it has a superior Jira integration, built-in CI/CD, & is free for up to 5 users.

- GitLab

GitLab offers git repository management, code reviews, issue tracking, activity feeds, and wikis. Enterprises install GitLab on-premise and connect it with LDAP and Active Directory servers for secure authentication and authorization. A single GitLab server can handle more than 25,000 users but it is also possible to create a high availability setup with multiple active servers.

- Atlassian Stash

It is a centralized solution to manage Git repositories behind the firewall. Streamlined for small agile teams, powerful enough for large organizations.


**Cost** 
I think it is worthwhile pointing out that GitHub Enterprise is available in a 45-day free trial. After that, it will cost the team to use the tool.

**Comment by santacruzm** [comment]
@bagashvilit Can you please specify what needs to be appended to the README.md file? I would like to help with clarification. Thanks!

**Comment by Jordan-A** [comment]
@santacruzm Personally think it would be great to add the background information about pygithub and its api to the readme.md FILE. I can add that to the readme file.

**Comment by Jordan-A** [comment]
I can confirm that the code runs for me when I added my token code. I also think that from a security standpoint it's not a great idea to share your one time token.

**Comment by Jordan-A** [comment]
I just pushed out an update that added more information to the readme file. It can be found here: https://github.com/GatorCogitate/cogitate_tool/commit/dd9b70d726dc0cda121174c2eb2c2d06cc5d3515.

**Comment by Jordan-A** [comment]
I just added three new features to our demo file! 🎉 It now welcomes the current user, searches the names of our research group, and outputs the current repository. I also removed the access token. It can be found at the following update: https://github.com/GatorCogitate/cogitate_tool/commit/309f31cb0d973138a2cf56ea150d288963d7d261

**Comment by Jordan-A** [comment]
I just added three MORE features to the demo file! 🎆 The update now returns a specific issue, gets the number of views on the repository for the past two weeks, and returns the milestone list. The last one currently returns nothing because we don't have a milestone list. The update can be found here: https://github.com/GatorCogitate/cogitate_tool/commit/b9977aafb672ee4b182e4e4c81065b366810a8fa .

**Comment by Jordan-A** [comment]
I just implemented three more features to demo.py! 😎 It now gets the contents of the root directory of the repository, finds one file in the root directory, and returns all the labels in the `cogitate_tool` repository. It can be found here: https://github.com/GatorCogitate/cogitate_tool/commit/d33840a40d3c2e423479396084c80721bd944113 .

**Comment by gkapfham** [comment]
Hi, I also wanted to point out that there are other tools that are also available, like this one:

[GitPython](https://github.com/gitpython-developers/GitPython)

Note that the developers of this tool acknowledge that there are some memory leaks in the system and thus it is not suitable for use on a long-running daemon. However, you should also consider using this and other packages if they have features that you think you might need.

Finally, @santacruzm, do you think that we need to use GitHub Enterprise for this project?

**Comment by santacruzm** [comment]
@gkapfham Consider the previous conversation on the Issue Tracker on the fact that the username and password method is not very reliable. I thought perhaps GitHub Enterprise could become a potential tool we can use on the project.

**Comment by santacruzm** [comment]
I implemented a link with further documentation on PyGitHub. You can find the changes here: [Documentation](https://github.com/GatorCogitate/cogitate_tool/commit/1e722bd178c9fe0a4505a91598ce108d714e6149)
